[package]
name = "mightty"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
eframe = { version = "0.31.1", default-features = false, features = ["accesskit", "default_fonts", "wayland", "wgpu"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
portable-pty = "0.9.0"
tokio = { version = "1.46.0", features = ["macros", "rt-multi-thread"] }
vte = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
xdg = "3.0.0"
