blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/julienmontagut/mightty/discussions
    about: Please use GitHub Discussions for questions and general discussion
  - name: Documentation
    url: https://github.com/julienmontagut/mightty/blob/main/README.md
    about: Check the README and documentation first