name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install scdoc
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin && rustup target add x86_64-apple-darwin
      - name: Test
        run: cargo test --release --target=x86_64-apple-darwin
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Upload Application
        run: |
          mv ./target/release/osx/Mightty.dmg ./Mightty-${GITHUB_REF##*/}.dmg
          ./.github/workflows/upload_asset.sh ./Mightty-${GITHUB_REF##*/}.dmg $GITHUB_TOKEN

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
            libxcb-xfixes0-dev libxkbcommon-dev python3 scdoc
      - name: Test
        run: cargo test --release
      - name: Generate manpages
        run: |
          scdoc < extra/man/mightty.1.scd | gzip -c > "./mightty.1.gz"
          scdoc < extra/man/mightty-msg.1.scd | gzip -c > "./mightty-msg.1.gz"
          scdoc < extra/man/mightty.5.scd | gzip -c > "./mightty.5.gz"
          scdoc < extra/man/mightty-bindings.5.scd | gzip -c > "./mightty-bindings.5.gz"
      - name: Upload Assets
        run: |
          mv ./extra/logo/mightty-term.svg ./Mightty.svg
          ./.github/workflows/upload_asset.sh ./Mightty.svg $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./mightty.1.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./mightty-msg.1.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./mightty.5.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./mightty-bindings.5.gz $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./extra/completions/mightty.bash $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./extra/completions/mightty.fish $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./extra/completions/_mightty $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./extra/linux/Mightty.desktop $GITHUB_TOKEN
          ./.github/workflows/upload_asset.sh ./extra/mightty.info $GITHUB_TOKEN
